# Generated by Django 4.0.4 on 2022-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('importance', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
