# Generated by Django 4.0.4 on 2022-04-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Тип задач',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='delo',
            options={'ordering': ['time'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='delo',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='delo',
            name='importance',
            field=models.SmallIntegerField(null=True, verbose_name='Важность задачи'),
        ),
        migrations.AlterField(
            model_name='delo',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Время задачи'),
        ),
        migrations.AlterField(
            model_name='delo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='delo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.type', verbose_name='Тип задачи'),
        ),
    ]
